# Generated by Django 5.2.10 on 2026-01-19 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('estimated_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('task_type', models.CharField(choices=[('deep_work', 'Travail en profondeur'), ('shallow', 'Tâche légère'), ('errand', 'Course/Admin')], default='shallow', max_length=20)),
                ('priority', models.PositiveIntegerField(default=5)),
                ('related_course', models.CharField(blank=True, max_length=100)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tâche',
                'verbose_name_plural': 'Tâches',
                'ordering': ['-priority', 'deadline', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('actually_completed', models.BooleanField(default=False)),
                ('actual_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_blocks', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_blocks', to='core.task')),
            ],
            options={
                'verbose_name': 'Bloc planifié',
                'verbose_name_plural': 'Blocs planifiés',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('document_type', models.CharField(choices=[('course_schedule', 'Horaire de cours'), ('work_schedule', 'Horaire de travail'), ('other', 'Autre')], default='other', max_length=20)),
                ('extracted_data', models.JSONField(blank=True, default=dict)),
                ('processed', models.BooleanField(default=False)),
                ('processing_error', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document uploadé',
                'verbose_name_plural': 'Documents uploadés',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='RecurringBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('block_type', models.CharField(choices=[('course', 'Cours'), ('work', 'Travail'), ('sleep', 'Sommeil'), ('other', 'Autre')], max_length=20)),
                ('day_of_week', models.PositiveIntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('is_night_shift', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_blocks', to=settings.AUTH_USER_MODEL)),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_blocks', to='core.uploadeddocument')),
            ],
            options={
                'verbose_name': 'Bloc récurrent',
                'verbose_name_plural': 'Blocs récurrents',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Utilisateur'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
                ('attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='core.uploadeddocument')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_sleep_hours', models.PositiveIntegerField(default=7)),
                ('post_night_shift_wake_time', models.TimeField(blank=True, null=True)),
                ('peak_productivity_time', models.CharField(choices=[('morning', 'Matin'), ('afternoon', 'Après-midi'), ('evening', 'Soir')], default='morning', max_length=20)),
                ('max_deep_work_hours_per_day', models.PositiveIntegerField(default=4)),
                ('transport_time_minutes', models.PositiveIntegerField(default=0)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('onboarding_step', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateurs',
            },
        ),
    ]
