# Generated by Django 5.2.10 on 2026-01-20 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringblock',
            name='block_type',
            field=models.CharField(choices=[('course', 'Cours'), ('work', 'Travail'), ('sleep', 'Sommeil'), ('meal', 'Repas'), ('sport', 'Sport'), ('project', 'Projet'), ('other', 'Autre')], max_length=20),
        ),
        migrations.CreateModel(
            name='RecurringBlockCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('recurring_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='core.recurringblock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Complétion bloc récurrent',
                'verbose_name_plural': 'Complétions blocs récurrents',
                'ordering': ['-date', '-completed_at'],
                'unique_together': {('recurring_block', 'date')},
            },
        ),
    ]
