# Generated by Django 5.2.10 on 2026-01-29 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_recurring_block_completion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=200)),
                ('task_type', models.CharField(max_length=20)),
                ('estimated_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('actual_duration_minutes', models.PositiveIntegerField()),
                ('scheduled_start_time', models.TimeField(blank=True, null=True)),
                ('day_of_week', models.PositiveIntegerField()),
                ('completed_at', models.DateTimeField()),
                ('energy_level', models.CharField(blank=True, max_length=10)),
                ('was_rescheduled', models.BooleanField(default=False)),
                ('reschedule_count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique tâche',
                'verbose_name_plural': 'Historique tâches',
                'ordering': ['-completed_at'],
                'indexes': [models.Index(fields=['user', 'task_type'], name='core_taskhi_user_id_097e5b_idx'), models.Index(fields=['user', 'task_title'], name='core_taskhi_user_id_c0077a_idx')],
            },
        ),
    ]
