# Generated by Django 5.2.10 on 2026-02-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userprofile_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddocument',
            name='file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='uploadeddocument',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
