# Generated by Django 5.2.10 on 2026-02-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_userprofile_preferred_llm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringblock',
            name='block_type',
            field=models.CharField(choices=[('course', 'Cours'), ('work', 'Travail'), ('sleep', 'Sommeil'), ('meal', 'Repas'), ('sport', 'Sport'), ('project', 'Projet'), ('revision', 'Révision'), ('other', 'Autre')], max_length=20),
        ),
    ]
