# Generated by Django 5.2.10 on 2026-07-21 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_goal_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='public_planning_enabled',
            field=models.BooleanField(default=False, help_text='Autorise le partage public du planning via /planning/<username>/'),
        ),
    ]
