# Generated by Django 5.2.10 on 2026-07-21 05:38

from django.conf import settings
from django.db import migrations, models


def backfill_completion_consistency(apps, schema_editor):
    """
    D9 backfill (additive, idempotent, safe on empty tables).

    For every already-completed Task:
      - mark all of its ScheduledBlocks actually_completed
      - fill a missing Task.completed_at (so the dedup key below is stable)
      - ensure a single TaskHistory row exists

    Never deletes or overwrites existing data. Dedup key for history is
    (user, task_title, completed_at); a re-run finds the existing row and
    skips it.
    """
    from django.utils import timezone

    Task = apps.get_model('core', 'Task')
    ScheduledBlock = apps.get_model('core', 'ScheduledBlock')
    TaskHistory = apps.get_model('core', 'TaskHistory')

    for task in Task.objects.filter(completed=True).iterator():
        # Fill a missing completion timestamp so the dedup key is stable.
        completed_at = task.completed_at
        if completed_at is None:
            completed_at = timezone.now()
            task.completed_at = completed_at
            task.save(update_fields=['completed_at'])

        blocks = list(ScheduledBlock.objects.filter(task=task))
        for block in blocks:
            if not block.actually_completed:
                block.actually_completed = True
                block.save(update_fields=['actually_completed'])

        already = TaskHistory.objects.filter(
            user_id=task.user_id,
            task_title=task.title,
            completed_at=completed_at,
        ).exists()
        if already:
            continue

        block = None
        if blocks:
            block = sorted(blocks, key=lambda b: (b.date, b.start_time))[0]

        if block is not None and block.actual_duration_minutes is not None:
            actual = block.actual_duration_minutes
        elif task.estimated_duration_minutes is not None:
            actual = task.estimated_duration_minutes
        else:
            actual = 0

        if block is not None:
            day_of_week = block.date.weekday()
            scheduled_start = block.start_time
        else:
            day_of_week = timezone.localtime(completed_at).weekday()
            scheduled_start = None

        TaskHistory.objects.create(
            user_id=task.user_id,
            task_title=task.title,
            task_type=task.task_type,
            estimated_duration_minutes=task.estimated_duration_minutes,
            actual_duration_minutes=actual,
            scheduled_start_time=scheduled_start,
            day_of_week=day_of_week,
            completed_at=completed_at,
        )


def noop_reverse(apps, schema_editor):
    """Reverse is a no-op: the backfill only adds/reconciles data additively."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_userprofile_public_planning_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='energy_levels',
            field=models.JSONField(blank=True, default=dict, help_text="Niveaux d'énergie par créneau (ex: {'morning': 'high', 'evening': 'low'})"),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notification_preferences',
            field=models.JSONField(blank=True, default=dict, help_text='Préférences de notifications (canaux, horaires, types activés)'),
        ),
        migrations.AddIndex(
            model_name='conversationmessage',
            index=models.Index(fields=['user', 'created_at'], name='convmsg_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringblock',
            index=models.Index(fields=['user', 'day_of_week', 'active'], name='recurblock_user_day_active_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledblock',
            index=models.Index(fields=['user', 'date'], name='schedblock_user_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='goal',
            constraint=models.CheckConstraint(condition=models.Q(('progress__gte', 0), ('progress__lte', 100)), name='goal_progress_between_0_and_100'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('priority__gte', 1), ('priority__lte', 10)), name='task_priority_between_1_and_10'),
        ),
        migrations.RunPython(backfill_completion_consistency, noop_reverse),
    ]
