# Generated by Django 5.2.10 on 2026-07-21 22:31

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_calendarfeed_webhookendpoint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recurringblock',
            options={'base_manager_name': 'all_objects', 'ordering': ['day_of_week', 'start_time'], 'verbose_name': 'Bloc récurrent', 'verbose_name_plural': 'Blocs récurrents'},
        ),
        migrations.AlterModelManagers(
            name='recurringblock',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='recurringblock',
            name='confidence',
            field=models.FloatField(blank=True, help_text="Confiance d'extraction 0-1 (null si créé manuellement).", null=True),
        ),
        migrations.AddField(
            model_name='recurringblock',
            name='status',
            field=models.CharField(choices=[('active', 'Actif'), ('pending', 'À confirmer')], db_index=True, default='active', help_text="'pending' = extrait mais en attente de confirmation utilisateur.", max_length=10),
        ),
    ]
