# Generated by Django 5.2.10 on 2026-07-21 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_recurringblock_confidence_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='prep_time_minutes',
            field=models.PositiveIntegerField(default=15, help_text='Temps de préparation avant de partir (minutes).'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='safety_margin_minutes',
            field=models.PositiveIntegerField(default=10, help_text='Marge de sécurité contre les retards (minutes).'),
        ),
        migrations.CreateModel(
            name='UserPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('home', 'Maison'), ('school', 'École'), ('work', 'Travail'), ('other', 'Autre')], default='other', max_length=10)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('travel_minutes', models.PositiveIntegerField(default=0, help_text='Durée habituelle du trajet depuis la maison (minutes).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lieu',
                'verbose_name_plural': 'Lieux',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='recurringblock',
            name='place',
            field=models.ForeignKey(blank=True, help_text="Lieu de l'activité ; son travel_minutes pilote l'heure limite de départ.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_blocks', to='core.userplace'),
        ),
        migrations.AddConstraint(
            model_name='userplace',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='userplace_user_name_unique'),
        ),
    ]
