# Generated by Django 5.2.10 on 2026-07-22 00:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_userplace_commute'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='auto_apply_threshold_minutes',
            field=models.PositiveIntegerField(default=60, help_text="En semi-auto: un déplacement au-delà de ce seuil est 'important' (proposé, pas appliqué)."),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='automation_mode',
            field=models.CharField(choices=[('suggestion', 'Suggestion (tout est proposé)'), ('semi_auto', 'Semi-automatique (petits changements auto)'), ('automatic', 'Automatique (déplace, explique, annulable)')], default='semi_auto', help_text="Niveau d'automatisation des réajustements (spec §8).", max_length=12),
        ),
        migrations.CreateModel(
            name='SchedulePlanChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date', models.DateField()),
                ('before', models.JSONField(default=list)),
                ('after', models.JSONField(default=list)),
                ('moved', models.JSONField(blank=True, default=list)),
                ('unplaced', models.JSONField(blank=True, default=list)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('proposed', 'Proposé'), ('applied', 'Appliqué'), ('undone', 'Annulé')], default='proposed', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Changement de planning',
                'verbose_name_plural': 'Changements de planning',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='core_schedu_user_id_a5b62d_idx')],
            },
        ),
    ]
