# Generated by Django 5.2.10 on 2026-07-23 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_automation_modes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledblock',
            name='locked',
            field=models.BooleanField(default=False, help_text='Sanctuaire : la replanification ne déplace jamais ce bloc.'),
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Accepté')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_connections', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Connexion',
                'verbose_name_plural': 'Connexions',
                'indexes': [models.Index(fields=['to_user', 'status'], name='core_connec_to_user_7fe737_idx')],
                'constraints': [models.UniqueConstraint(fields=('from_user', 'to_user'), name='connection_unique_pair')],
            },
        ),
    ]
