# Generated by Django 5.2.10 on 2026-07-23 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_locked_and_connection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringBlockException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recurring_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='core.recurringblock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_exceptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exception bloc récurrent',
                'verbose_name_plural': 'Exceptions blocs récurrents',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'date'], name='core_recurr_user_id_d01788_idx')],
                'unique_together': {('recurring_block', 'date')},
            },
        ),
    ]
