# Generated by Django 5.2.10 on 2026-07-23 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_recurring_block_exception'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='core.userplace'),
        ),
        migrations.AddField(
            model_name='userplace',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userplace',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
