# Generated by Django 5.2.10 on 2026-07-23 22:19

from django.db import migrations, models


def backfill_recurringblock_flexibility(apps, schema_editor):
    RecurringBlock = apps.get_model('core', 'RecurringBlock')
    fixed_types = ['work', 'course']
    RecurringBlock.objects.filter(block_type__in=fixed_types).update(
        flexibility='fixed'
    )
    RecurringBlock.objects.exclude(block_type__in=fixed_types).update(
        flexibility='flexible'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_task_place_and_userplace_coords'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringblock',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text="Durée cible d'un bloc souple; si null, dérivée de end-start.", null=True),
        ),
        migrations.AddField(
            model_name='recurringblock',
            name='flexibility',
            field=models.CharField(blank=True, choices=[('fixed', 'Fixe'), ('flexible', 'Souple')], db_index=True, max_length=10, null=True),
        ),
        migrations.RunPython(
            backfill_recurringblock_flexibility,
            migrations.RunPython.noop,
        ),
    ]
