# Generated by Django 5.2.10 on 2026-07-28 06:22

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_recurringblock_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadeddocument',
            name='file',
            field=models.FileField(storage=core.models.document_file_storage, upload_to=core.models.document_upload_to),
        ),
    ]
