# Generated by Django 5.2.10 on 2026-07-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_document_raw_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_llm',
            field=models.CharField(choices=[('gemini', 'Gemini (Google)'), ('claude', 'Claude (Anthropic)'), ('deepseek', 'DeepSeek (raisonnement)')], default='gemini', help_text='Modèle IA préféré pour le chat', max_length=20),
        ),
    ]
