# Generated by Django 5.2.10 on 2026-08-04 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_daily_brain_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='McpOAuthCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('client_id', models.CharField(max_length=255)),
                ('redirect_uri', models.TextField()),
                ('redirect_uri_explicit', models.BooleanField(default=True)),
                ('code_challenge', models.CharField(max_length=128)),
                ('scopes', models.JSONField(default=list)),
                ('resource', models.TextField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_oauth_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['code'], name='core_mcpoau_code_205198_idx')],
            },
        ),
    ]
