# Generated by Django 5.2.10 on 2026-08-05 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_mcp_oauth_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringblock',
            name='end_date',
            field=models.DateField(blank=True, help_text="Derniere date ou le bloc s'applique (null = sans fin).", null=True),
        ),
        migrations.AddField(
            model_name='recurringblock',
            name='start_date',
            field=models.DateField(blank=True, help_text="Premiere date ou le bloc s'applique (null = depuis toujours).", null=True),
        ),
    ]
