# Generated by Django 5.2.10 on 2026-08-10 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_recurring_block_date_bounds'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSendLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('block_soon', 'Bloc bientot'), ('block_prep', 'Bloc preparation'), ('block_leave', 'Bloc depart'), ('task_prep', 'Tache preparation'), ('task_leave', 'Tache depart')], max_length=24)),
                ('ref', models.CharField(max_length=40)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_send_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'date'], name='core_pushse_user_id_028857_idx')],
                'unique_together': {('user', 'kind', 'ref', 'date')},
            },
        ),
    ]
