# Generated by Django 5.2.10 on 2026-08-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_push_send_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='apple_client_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='apple_refresh_token',
            field=models.TextField(blank=True, default=''),
        ),
    ]
