# Generated by Django 5.2.10 on 2026-08-14 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_apple_refresh_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ai_consent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
