# Generated by Django 5.2.10 on 2026-08-26 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_ai_consent'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='agent_v2',
            field=models.BooleanField(default=False),
        ),
    ]
