# Generated by Django 5.2.10 on 2026-09-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_reveil_apns'),
    ]

    operations = [
        migrations.AddField(
            model_name='reveilplanning',
            name='confirme_a',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reveilplanning',
            name='relances',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
