# Generated by Django 5.2.10 on 2026-09-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_reveil_confirme'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedschedule',
            name='scope',
            field=models.CharField(choices=[('week', 'Semaine'), ('today', 'Journée')], default='week', max_length=10),
        ),
    ]
