# Generated by Django 5.2.10 on 2026-09-17 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_partage_journee'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deliverable',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='depends_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependents', to='core.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='done_when',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='core.goal'),
        ),
    ]
