# Generated by Django 5.2.10 on 2026-09-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_taches_livrable_objectif_dependance'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='voix_agir',
            field=models.BooleanField(default=False),
        ),
    ]
