# Generated by Django 5.2.17 on 2026-09-28 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_budgetjetonsjournalier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenceUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enonce', models.CharField(help_text="Preference en une ou deux phrases, telle que l'agent doit l'appliquer.", max_length=500)),
                ('categorie', models.CharField(choices=[('horaire', 'Horaire'), ('lieu', 'Lieu'), ('personne', 'Personne'), ('habitude', 'Habitude'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('source', models.CharField(choices=[('dite', 'Dite explicitement'), ('inferee', 'Inferee puis confirmee')], default='dite', max_length=10)),
                ('confiance', models.FloatField(default=1.0, help_text='1.0 = dite explicitement, < 1.0 = inferee puis confirmee.')),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences_memoire', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Préférence mémorisée',
                'verbose_name_plural': 'Préférences mémorisées',
                'ordering': ['-updated_at'],
            },
        ),
    ]
