# Generated by Django 5.2.17 on 2026-09-28
#
# Compte anonyme (mode sans inscription, modele Firebase Anonymous Auth).
# Numero 0038 et pas 0037 : le 0037 est reserve au lot memoire-preferences
# (PR #6, branche feat/memoire-preferences-agent). La dependance vise donc
# 0036 directement.
#
# ATTENTION au merge : si la PR #6 est mergee avant celle-ci, main aura deux
# migrations feuilles (0037 et 0038 toutes deux issues de 0036). Django
# refuse alors de creer de nouvelles migrations ("Conflicting migrations
# detected") : il faudra une migration de fusion (0039_merge) ou rebaser ce
# lot sur 0037. Ordre de merge a trancher avec Darius avant de merger.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_budgetjetonsjournalier'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='device_id',
            field=models.CharField(blank=True, help_text="Identifiant d'appareil pour la reprise d'un compte anonyme.", max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_anonymous',
            field=models.BooleanField(default=False, help_text='Compte sans inscription, lie a un appareil via device_id.'),
        ),
    ]
