# Generated by Django 5.2.10 on 2026-09-28 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_memoire_preferences'),
        ('core', '0038_auth_anonyme'),
    ]

    operations = [
    ]
